spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      mvc:
        routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/users/**

        - id: HotelService
          uri: lb://HotelService
          predicates:
            - Path=/hotels/**
            
        - id: RatingService
          uri: lb://RatingService
          predicates:
            - Path=/ratings/**
  
  config:
    import: optional:configserver:http://localhost:8085


server:
  port: 8084
