server:
  port: 8085

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prabeshkunwar12/hotel_rating
          clone-on-start: true
          basedir:
            name: ConfigProperties