server:
    port: 8081

spring:
  application:
    name: UserService
    
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_rating
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: optional:configserver:http://localhost:8085

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health   
  endpoint:
    health:
      show-details: always   

resilience4j:
  circuitbreaker:
    instances:
      getUserCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      getAllUsersCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      getAllUsersRetry: 
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      getAllUsersRateLimitor:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 2s
