server:
  port: 8083

spring:
  application:
    name: RatingService

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: hotel_rating
  
  config:
    import: optional:configserver:http://localhost:8085
